bancf = [{ami : 'AMI455',
             numRapport : 'XXX',
            emetteur : 'LAFON ASSEMBLAGE',
            up : 'Automation',
            date : '24/10/2019',
            codeArticle : '17681000',
            indice : 'A',
            designation : 'Automate APL3',
            qte : 3,
            numSerie : ['1905-001','1905-001','1905-001','1905-001','1905-001'],
            anomalie : 'Ne fonctionne pas',
            fournisseur : 'GLOBALCOM',
            of : 'EQD001',
            commande : 'CF16584',
            avancement : 'Attente d\'analyse',
            dateCloture : '',
            responsableAction : 'Rémi Archambault',
            coutUnitaire : 1700},
			{ami : 'AMI454',
             numRapport : 'XXX',
            emetteur : 'LAFON ASSEMBLAGE',
            up : 'Automation',
            date : '24/10/2019',
            codeArticle : '17681000',
            indice : 'A',
            designation : 'Automate APL3',
            qte : 5,
            numSerie : ['1905-001','1905-001','1905-001','1905-001','1905-001'],
            anomalie : 'Ne fonctionne pas',
            fournisseur : 'GLOBALCOM',
            of : 'EQD001',
            commande : 'CF16584',
            avancement : 'Attente d\'analyse',
            dateCloture : '',
            responsableAction : 'Rémi Archambault',
            coutUnitaire : 100}
]